dist: xenial
language: python

# When adding a version here, remember to change it in setup.py
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - python setup.py --quiet install
    - pip --quiet install -r test-requirements.txt

script:
    - python setup.py --quiet test

after_success:
    - coverage run --source circlify tests.py
    - coveralls
